# Generated by Django 3.2.4 on 2021-06-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(choices=[('Corporate Headoffice', 'Corporate Headpffice'), ('Operations Department', 'Operations Department'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], max_length=50),
        ),
    ]
