# Generated by Django 3.2.4 on 2021-06-27 15:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mart', '0003_alter_incident_sub_incident_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='sub_incident_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Environmental Incident', 'Environmental Incident'), ('Injury/Illness', 'Injury/Illness'), ('Property Damage', 'Property Damage'), ('Vehicle', 'Vehicle')], max_length=100), size=None), size=None),
        ),
    ]
